# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: true
os:
  - linux
notifications:
  email:
    - frank@mirsem.org
    - viola.pausch@posteo.de
    - kilian.sander@aol.com
    - kgf@omniversum.de

before_deploy: Rscript -e 'remotes::install_cran("pkgdown"); remotes::install_github("rstudio/rmarkdown"); install.packages("shinytest"); shinytest::installDependencies()'

after_success:
  - Rscript -e 'covr::codecov()'

#deploy:
#  provider: script
#  script: Rscript -e 'pkgdown::deploy_site_github()'
#  skip_cleanup: true
