# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: true
os:
  - linux
notifications:
  email:
    - fmhoeger@mirsem.org

before_deploy: Rscript -e 'remotes::install_cran("pkgdown"); remotes::install_github("rstudio/rmarkdown"); install.packages("shinytest"); shinytest::installDependencies()'

r_packages:
  - covr
  - devtools

r_github_packages:
  - fmhoeger/MIQ

after_success:
  - Rscript -e 'library(covr);codecov()'
